on:
  push:
    branch:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - run: |
          ./gradlew build --no-daemon --scan -PparallelTests=true
